### ISSUE TITLE
How to get the user location

### ISSUE THREAD

**Issue by farhadwahaj** [zyra/ngx-facebook-example#5]
Hi i am trying to find a way to get the user location, can any one please help me.
tryd:
this.fb.api('/me?fields=first_name, last_name, picture, email, cover, gender, locale,location')
.then((res: any) => this.profile = res )
.catch((error:any) => alert(error));
}

but its not working would really appreciet help.

**Comment by ihadeed** [comment]
See https://stackoverflow.com/questions/19853162/how-to-get-user-location-and-user-hometown-in-facebook-api/19853997
